# -*- coding: utf-8 -*-
"""Gera content.js com mensagens, dietas, histórias e dicas de clima."""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parent

def fill(templates, nome):
    return [t.replace("{{nome}}", nome) for t in templates]

def uniq(items):
    seen, out = set(), []
    for x in items:
        if x not in seen:
            seen.add(x)
            out.append(x)
    return out

def enlarge(lst):
    extra = []
    for i, m in enumerate(lst):
        if i % 3 == 0 and "Assim seja" not in m:
            extra.append(m + " Assim seja.")
        if i % 4 == 0:
            extra.append(m.replace("Que a ", "Que hoje a ").replace("Que o ", "Que hoje o ", 1))
        if i % 7 == 0:
            extra.append(m.replace("Deus", "o Senhor"))
    return uniq(lst + extra)

MANHA = [
"Bom dia, {{nome}}. Que a paz de Deus abençoe o seu despertar e encha sua casa de serenidade.",
"Bom dia, {{nome}}. Que este amanhecer traga saúde, fé e um coração leve.",
"Bom dia, {{nome}}. Cada manhã é um presente — receba-o com gratidão e esperança.",
"Bom dia, {{nome}}. Que os bons espíritos acompanhem seus passos desde o primeiro instante.",
"Bom dia, {{nome}}. Que a luz deste dia aqueça sua alma e renove suas forças.",
"Bom dia, {{nome}}. Comece o dia com uma prece suave e a certeza de que é amado(a).",
"Bom dia, {{nome}}. Que a bondade floresça em cada gesto seu nesta manhã.",
"Bom dia, {{nome}}. Que Deus guarde sua saúde e ilumine seus pensamentos.",
"Bom dia, {{nome}}. Um novo dia começa — e com ele, novas bênçãos.",
"Bom dia, {{nome}}. Que a calma seja sua companheira desde cedo.",
"Bom dia, {{nome}}. Que seu coração acorde leve, confiante e protegido.",
"Bom dia, {{nome}}. Que a fé abra caminhos bonitos para você hoje.",
"Bom dia, {{nome}}. Que o Senhor abençoe sua manhã com saúde e tranquilidade.",
"Bom dia, {{nome}}. Que cada respiração desta manhã lembre você da graça de viver.",
"Bom dia, {{nome}}. Que a alegria simples encontre espaço no seu coração hoje.",
"Bom dia, {{nome}}. Que Deus renove suas forças e suavize qualquer preocupação.",
"Bom dia, {{nome}}. Que este dia seja gentil com você.",
"Bom dia, {{nome}}. Que a luz do Criador ilumine sua casa e seu espírito.",
"Bom dia, {{nome}}. Que a esperança seja a primeira visita da sua manhã.",
"Bom dia, {{nome}}. Que o bem que você planta retorne em bênçãos abundantes.",
"Bom dia, {{nome}}. Que o Amor Divino cubra você com um manto de serenidade.",
"Bom dia, {{nome}}. Que este amanhecer marque um recomeço suave e abençoado.",
"Bom dia, {{nome}}. Que a gratidão abra seus olhos para as pequenas maravilhas.",
"Bom dia, {{nome}}. Que você caminhe hoje cercado(a) de anjos e de boas intenções.",
"Bom dia, {{nome}}. Que a paz more em sua mente e a fé em seu peito.",
"Bom dia, {{nome}}. Que Deus abençoe suas mãos, suas palavras e seu coração.",
"Bom dia, {{nome}}. Que a manhã traga clareza, saúde e um sorriso sincero.",
"Bom dia, {{nome}}. Lembre-se: você é importante, amado(a) e nunca está sozinho(a).",
"Bom dia, {{nome}}. Que o Espírito Santo inspire seus pensamentos desde cedo.",
"Bom dia, {{nome}}. Que este dia seja tecido com paciência, amor e fé.",
"Bom dia, {{nome}}. Que a natureza de Venâncio Aires lhe deseje um lindo dia.",
"Bom dia, {{nome}}. Que cada hora deste dia seja envolvida em oração e carinho.",
"Bom dia, {{nome}}. Que o Senhor afaste o medo e plante coragem suave em você.",
"Bom dia, {{nome}}. Que a alegria da família aqueça sua manhã.",
"Bom dia, {{nome}}. Que você desfrute deste dia com leveza e confiança em Deus.",
"Bom dia, {{nome}}. Que a saúde se fortaleça e a alma se alegre neste despertar.",
"Bom dia, {{nome}}. Que uma mensagem de amor chegue ao seu coração logo cedo.",
"Bom dia, {{nome}}. Que o café da manhã venha com paz e o dia com esperança.",
"Bom dia, {{nome}}. Que Thomas, Nicolas e Chris estejam presentes em seus pensamentos com carinho.",
"Bom dia, {{nome}}. Que você tenha forças para o que precisar e descanso para o que pesar.",
"Bom dia, {{nome}}. Que a caridade comece em casa e se espalhe pelo seu dia.",
"Bom dia, {{nome}}. Que Deus guarde seus passos na rua, no quintal e em cada tarefa.",
"Bom dia, {{nome}}. Que a fé seja maior do que qualquer inquietação da manhã.",
"Bom dia, {{nome}}. Que o sol de Venâncio Aires aqueça o corpo e a alma.",
"Bom dia, {{nome}}. Que você sinta um abraço invisível do Thomas neste despertar.",
"Bom dia, {{nome}}. Que a oração da manhã abra portas de paz para toda a família.",
"Bom dia, {{nome}}. Que o dia traga encontros gentis e palavras boas.",
"Bom dia, {{nome}}. Que o Senhor multiplique alegrias simples na sua rotina.",
"Bom dia, {{nome}}. Que a água, o ar e o alimento de hoje sejam bênçãos reconhecidas.",
"Bom dia, {{nome}}. Que a saúde do corpo e a paz da alma caminhem juntas hoje.",
]

TARDE = [
"Boa tarde, {{nome}}. Que a paz continue acompanhando o restante do seu dia.",
"Boa tarde, {{nome}}. Pause um instante, respire e lembre que Deus cuida de você.",
"Boa tarde, {{nome}}. Que a luz da tarde suavize o cansaço e renove a esperança.",
"Boa tarde, {{nome}}. Que sua tarde seja leve, produtiva e abençoada.",
"Boa tarde, {{nome}}. Um gole de água, uma prece curta e o coração em paz.",
"Boa tarde, {{nome}}. Que o bem que você fez pela manhã floresça agora.",
"Boa tarde, {{nome}}. Que Deus fortaleça sua saúde neste meio do dia.",
"Boa tarde, {{nome}}. Que a serenidade visite sua casa nesta tarde.",
"Boa tarde, {{nome}}. Que qualquer preocupação encontre alívio na fé.",
"Boa tarde, {{nome}}. Que o sol da tarde lembre você da constância do Amor Divino.",
"Boa tarde, {{nome}}. Que você se sinta amparado(a) e querido(a).",
"Boa tarde, {{nome}}. Que a gratidão transforme o restante do dia.",
"Boa tarde, {{nome}}. Que os anjos guardem sua casa nesta tarde.",
"Boa tarde, {{nome}}. Que a paciência seja sua companheira agora.",
"Boa tarde, {{nome}}. Que o Senhor abençoe seu corpo, mente e espírito.",
"Boa tarde, {{nome}}. Que a família esteja unida em pensamento e em oração.",
"Boa tarde, {{nome}}. Que um sorriso suave ilumine sua face neste instante.",
"Boa tarde, {{nome}}. Que a esperança não falte mesmo nos minutos cansados.",
"Boa tarde, {{nome}}. Que você encontre descanso mesmo em meio às tarefas.",
"Boa tarde, {{nome}}. Que a caridade e a gentileza marquem sua tarde.",
"Boa tarde, {{nome}}. Que Deus afaste o mal e aproxime a paz.",
"Boa tarde, {{nome}}. Que a brisa de Venâncio Aires traga frescor e calma.",
"Boa tarde, {{nome}}. Que seu coração continue confiante no cuidado divino.",
"Boa tarde, {{nome}}. Que o Thomas envie, de longe, um abraço cheio de amor.",
"Boa tarde, {{nome}}. Que a fé renove o ânimo para o que ainda falta no dia.",
"Boa tarde, {{nome}}. Que a saúde se conserve e a alegria se faça presente.",
"Boa tarde, {{nome}}. Que você se lembre de beber água e cuidar de si.",
"Boa tarde, {{nome}}. Que a oração da tarde limpe a mente e acalme a alma.",
"Boa tarde, {{nome}}. Que o Senhor abençoe cada passo que você ainda der hoje.",
"Boa tarde, {{nome}}. Que a luz dourada da tarde aqueça seus pensamentos.",
"Boa tarde, {{nome}}. Que o bem esteja em suas palavras e atitudes agora.",
"Boa tarde, {{nome}}. Que a tranquilidade more em sua casa nesta hora.",
"Boa tarde, {{nome}}. Que Deus multiplique motivos simples para sorrir.",
"Boa tarde, {{nome}}. Que a tarde seja um convite ao equilíbrio e à fé.",
"Boa tarde, {{nome}}. Que você sinta proteção em cada detalhe do dia.",
"Boa tarde, {{nome}}. Que a alma encontre um instante de silêncio santo.",
"Boa tarde, {{nome}}. Que o amor da família envolva você agora.",
"Boa tarde, {{nome}}. Que o cansaço se transforme em descanso merecido.",
"Boa tarde, {{nome}}. Que a graça de Deus seja visível nos pequenos gestos.",
"Boa tarde, {{nome}}. Que a esperança continue acesa até o entardecer.",
"Boa tarde, {{nome}}. Que o Senhor guarde sua saúde nesta tarde gaúcha.",
"Boa tarde, {{nome}}. Que a paz do Cristo suavize qualquer inquietação.",
"Boa tarde, {{nome}}. Que você se sinta valorizado(a) e importante.",
"Boa tarde, {{nome}}. Que a oração una sua casa em harmonia.",
"Boa tarde, {{nome}}. Que o bem devolvido à vida retorne em bênçãos.",
"Boa tarde, {{nome}}. Que a fé seja o sol que não se põe no seu coração.",
"Boa tarde, {{nome}}. Que a tarde traga notícias boas e encontros gentis.",
"Boa tarde, {{nome}}. Que Deus ilumine decisões e acalme memórias difíceis.",
"Boa tarde, {{nome}}. Que o restante do dia seja leve como uma prece.",
"Boa tarde, {{nome}}. Que você caminhe com confiança até a noite chegar.",
]

NOITE = [
"Boa noite, {{nome}}. Que o Senhor guarde o seu sono com paz e proteção.",
"Boa noite, {{nome}}. Entregue o dia nas mãos de Deus e descanse o coração.",
"Boa noite, {{nome}}. Que os anjos vigiem sua casa enquanto você dorme.",
"Boa noite, {{nome}}. Que a noite traga descanso profundo e sonhos suaves.",
"Boa noite, {{nome}}. Que a oração da noite limpe preocupações e plante fé.",
"Boa noite, {{nome}}. Que o Arcanjo Miguel proteja seu repouso.",
"Boa noite, {{nome}}. Que a gratidão feche o dia e a esperança abra o amanhã.",
"Boa noite, {{nome}}. Que Deus abençoe sua saúde nesta noite.",
"Boa noite, {{nome}}. Que a lua e as estrelas lembrem você do cuidado divino.",
"Boa noite, {{nome}}. Que o silêncio da noite seja um abraço para a alma.",
"Boa noite, {{nome}}. Que o perdão e a paz acompanhem seu travesseiro.",
"Boa noite, {{nome}}. Que nenhum medo tenha espaço no seu descanso.",
"Boa noite, {{nome}}. Que a família esteja unida em oração nesta noite.",
"Boa noite, {{nome}}. Que o Senhor renove suas forças enquanto você dorme.",
"Boa noite, {{nome}}. Que a serenidade cubra sua casa como um manto.",
"Boa noite, {{nome}}. Que você sinta o carinho dos filhos neste momento.",
"Boa noite, {{nome}}. Que a fé acenda uma luz suave no escuro.",
"Boa noite, {{nome}}. Que o corpo descanse e a alma se alegre em Deus.",
"Boa noite, {{nome}}. Que a noite de Venâncio Aires seja tranquila e abençoada.",
"Boa noite, {{nome}}. Que cada respiração leve você a um sono reparador.",
"Boa noite, {{nome}}. Que o Amor Divino afaste inquietações e traga calma.",
"Boa noite, {{nome}}. Que amanhã amanheça com saúde e esperança renovadas.",
"Boa noite, {{nome}}. Que a oração do Arcanjo Miguel acompanhe seu sono.",
"Boa noite, {{nome}}. Que Deus guarde a porta, a janela e o coração da casa.",
"Boa noite, {{nome}}. Que o cansaço se dissolva no descanso merecido.",
"Boa noite, {{nome}}. Que a paz de Cristo habite seus pensamentos agora.",
"Boa noite, {{nome}}. Que você se lembre do quanto é amado(a) antes de dormir.",
"Boa noite, {{nome}}. Que o Senhor abençoe o Osvaldo, a Ivone e toda a família.",
"Boa noite, {{nome}}. Que a noite seja leve e o despertar seja doce.",
"Boa noite, {{nome}}. Que anjos da guarda fiquem ao lado da sua cama.",
"Boa noite, {{nome}}. Que a gratidão pelo dia feche este capítulo com amor.",
"Boa noite, {{nome}}. Que nenhuma preocupação roube a doçura do sono.",
"Boa noite, {{nome}}. Que a fé seja o último pensamento antes de dormir.",
"Boa noite, {{nome}}. Que Deus multiplique bênçãos sobre sua casa nesta noite.",
"Boa noite, {{nome}}. Que o silêncio sagrado acalme a mente.",
"Boa noite, {{nome}}. Que o Thomas envie um beijo de boa noite cheio de carinho.",
"Boa noite, {{nome}}. Que a proteção divina cubra cada canto do lar.",
"Boa noite, {{nome}}. Que o amanhã nasça melhor, mais leve e mais feliz.",
"Boa noite, {{nome}}. Que a alma entregue tudo a Deus e descanse.",
"Boa noite, {{nome}}. Que a noite traga cura suave ao corpo e ao espírito.",
"Boa noite, {{nome}}. Que o Senhor ouça sua prece e acalme seu peito.",
"Boa noite, {{nome}}. Que o sono venha fácil e o coração fique em paz.",
"Boa noite, {{nome}}. Que a luz de Deus brilhe mesmo no escuro da noite.",
"Boa noite, {{nome}}. Que a família durma sob a mesma bênção, mesmo à distância.",
"Boa noite, {{nome}}. Que o bem feito hoje retorne em sonhos bons.",
"Boa noite, {{nome}}. Que a misericórdia divina cubra o que faltou e o que doeu.",
"Boa noite, {{nome}}. Que você durma protegido(a), amado(a) e em paz.",
"Boa noite, {{nome}}. Que a oração da noite seja um porto seguro.",
"Boa noite, {{nome}}. Que Deus diga amém sobre o seu descanso.",
"Boa noite, {{nome}}. Descanse com fé. Amanhã a vida continua com esperança.",
]

greetings = {
    "morning": {
        "ivone": enlarge(fill(MANHA, "Ivone") + [
            "Bom dia, mamãe Ivone. Que você sinta o amor dos seus filhos neste despertar.",
            "Bom dia, Ivone. Receba este abraço do Thomas: você é muito especial.",
            "Bom dia, mamãe. Que sua fé continue iluminando nossa família.",
        ]),
        "osvaldo": enlarge(fill(MANHA, "Osvaldo") + [
            "Bom dia, papai Osvaldo. Que Deus abençoe sua força e sua saúde.",
            "Bom dia, Osvaldo. Que este dia honre o cuidado que você tem com a família.",
            "Bom dia, pai. Que sua manhã seja firme, serena e abençoada.",
        ]),
    },
    "afternoon": {
        "ivone": enlarge(fill(TARDE, "Ivone") + [
            "Boa tarde, mamãe Ivone. Que o carinho dos filhos aqueça sua tarde.",
            "Boa tarde, Ivone. Pause, beba água e sinta-se amada.",
        ]),
        "osvaldo": enlarge(fill(TARDE, "Osvaldo") + [
            "Boa tarde, papai Osvaldo. Que sua tarde seja forte e tranquila.",
            "Boa tarde, Osvaldo. Que Deus renove sua disposição e sua paz.",
        ]),
    },
    "evening": {
        "ivone": enlarge(fill(NOITE, "Ivone") + [
            "Boa noite, mamãe Ivone. Descanse no amor de Deus e dos seus filhos.",
            "Boa noite, Ivone. Que o Arcanjo Miguel guarde seu sono.",
        ]),
        "osvaldo": enlarge(fill(NOITE, "Osvaldo") + [
            "Boa noite, papai Osvaldo. Que Deus guarde seu descanso e sua saúde.",
            "Boa noite, Osvaldo. Durma em paz — sua família agradece por você.",
        ]),
    },
}

daily_messages = uniq([
"Que o seu coração encontre hoje a calma necessária para perceber que cada amanhecer é uma nova oportunidade.",
"A fé não elimina todos os caminhos difíceis, mas acende uma luz para que possamos atravessá-los.",
"Faça o bem que estiver ao seu alcance. Muitas vezes, uma pequena gentileza transforma um dia inteiro.",
"A serenidade cresce quando confiamos que cada experiência pode ensinar algo à nossa alma.",
"Não carregue hoje o peso de todos os dias. Viva este momento com esperança e confiança.",
"A paz começa dentro de nós quando escolhemos pensamentos mais suaves e atitudes mais amorosas.",
"Mesmo nos dias silenciosos, a vida continua preparando novos encontros, aprendizados e alegrias.",
"Cada gesto de carinho é uma semente de luz plantada no caminho de alguém.",
"Você não precisa ter todas as respostas. Basta seguir com fé, bondade e um passo de cada vez.",
"A esperança é a voz tranquila da alma lembrando que nenhuma noite dura para sempre.",
"Perdoar não muda o passado, mas pode devolver leveza ao presente.",
"O amor que oferecemos sempre encontra uma forma de permanecer no mundo.",
"Cuide dos seus pensamentos como quem cuida de um jardim: retire o que machuca e regue o que traz paz.",
"A espiritualidade também vive nas coisas simples: uma palavra gentil, um abraço sincero e uma prece feita com amor.",
"Confie no tempo, mas faça hoje tudo o que estiver ao seu alcance para espalhar o bem.",
"A verdadeira força é continuar cultivando ternura, mesmo depois de dias difíceis.",
"Que a sua casa seja hoje um lugar de paz e que seu coração seja um abrigo de esperança.",
"Você faz parte de uma história maior, construída com aprendizados, reencontros e oportunidades de evolução.",
"A gratidão transforma o que temos em suficiente e abre os olhos para bênçãos antes despercebidas.",
"Não compare o seu caminho. Cada alma possui seu próprio tempo de florescer.",
"Onde houver dúvida, escolha a bondade. Onde houver medo, faça uma prece.",
"A vida sempre oferece uma nova página. Escreva a de hoje com fé e serenidade.",
"Toda dificuldade pode ser atravessada com mais leveza quando caminhamos também com esperança.",
"Que seus pensamentos encontrem repouso e sua alma se lembre do quanto é amada.",
"Ser paciente consigo mesma também é uma forma de caridade.",
"A luz que você oferece aos outros também ilumina o seu próprio caminho.",
"Nenhum esforço sincero para ser melhor é pequeno.",
"A prece é uma conversa da alma: não precisa ser perfeita, apenas verdadeira.",
"O dia de hoje não precisa ser extraordinário para ser precioso.",
"Que você reconheça, nas pequenas alegrias, a presença delicada do amor divino.",
"A cada manhã, a vida nos convida novamente a aprender, amar, perdoar e recomeçar.",
"Cuidar da saúde também é uma forma de gratidão pela vida.",
"Beber água, respirar fundo e sorrir são pequenos atos de amor próprio.",
"A família se fortalece quando cada um oferece paciência e compreensão.",
"Que a casa de Ivone e Osvaldo seja sempre um refúgio de fé.",
"O bem feito em silêncio também chega ao céu.",
"Uma palavra mansa pode acalmar uma tempestade no coração.",
"Que a humildade guie as decisões e a caridade inspire as ações.",
"Hoje é um bom dia para agradecer, perdoar e recomeçar.",
"A fé verdadeira se mostra no cuidado com quem está perto.",
"Que a paz de Venâncio Aires entre pela janela e more na alma.",
"Não há noite tão escura que a oração não possa iluminar.",
"Que o trabalho das mãos seja abençoado e o descanso seja santo.",
"Amar é também saber ouvir, esperar e acompanhar com doçura.",
"Que a saúde do corpo caminhe junto com a saúde do espírito.",
"Cada refeição feita com gratidão se torna quase uma prece.",
"Que a união da família vença qualquer distância.",
"O perdão libera quem perdoa tanto quanto quem é perdoado.",
"Que a esperança seja cultivada como quem cuida de uma planta.",
"Hoje, escolha pensamentos que edifiquem e palavras que curem.",
"A coragem de pedir ajuda também é uma virtude.",
"Que Deus abençoe o pão, a água e o afeto desta casa.",
"Pequenos hábitos saudáveis constroem longos dias de bem-estar.",
"Que a oração una Ivone, Osvaldo e os filhos em um só coração.",
"A paciência é uma ponte entre a angústia e a paz.",
"Que o tempo de Deus seja aceito com confiança e serenidade.",
"Fazer o bem sem esperar retorno já é uma grande recompensa.",
"Que a alegria simples visite a rotina de vocês hoje.",
"A luz interior cresce quando cultivamos gratidão sincera.",
"Que o Senhor guarde a saúde de toda a família.",
"Em cada clima — sol, chuva ou vento — há uma lição de cuidado.",
"Que a caridade comece no olhar gentil dentro de casa.",
"A fé não apressa o milagre, mas sustenta a caminhada.",
"Que o dia de hoje seja marcado por gestos de cuidado mútuo.",
"Beber água é um lembrete simples: sua vida merece atenção.",
"Que a noite encontre vocês em paz e o dia em esperança.",
"A bondade praticada todos os dias muda o destino de uma casa.",
"Que o Amor Divino seja o centro das decisões de vocês.",
"Hoje, ofereça a alguém um pouco da paz que você deseja receber.",
"Que a sabedoria dos anos se una à doçura do coração.",
"Cuidar um do outro é a mais bela oração em família.",
"Que a graça de Deus multiplique o que for feito com amor.",
"A alma descansa quando a consciência está em paz.",
"Que Ivone e Osvaldo sintam, em cada mensagem, o abraço do Thomas.",
"O bem é contagioso: espalhe-o com naturalidade.",
"Que a saúde mental e espiritual sejam cuidadas com o mesmo zelo.",
"Em dias difíceis, volte à prece; em dias fáceis, volte à gratidão.",
"Que o Espírito de verdade inspire palavras e silêncios.",
"A casa feliz se constrói com respeito, fé e afeto diário.",
"Que a bênção de Deus repouse sobre Venâncio Aires e sobre vocês.",
"Hoje é dia de lembrar: vocês não caminham sozinhos.",
"Que a esperança cristã fortaleça o corpo e a alma.",
"A generosidade abre caminhos onde o egoísmo fecha portas.",
"Que o amor fraterno entre Thomas, Nicolas e Chris alegre os pais.",
"Pequenas vitórias diárias também merecem celebração.",
"Que a paz seja escolhida, cultivada e compartilhada.",
"O Senhor conhece cada necessidade — confie e faça a sua parte.",
"Que a oração da manhã guie e a da noite console.",
"A saúde se agradece cuidando dela com constância.",
"Que a fé racional e o sentimento nobre caminhem juntos.",
"Hoje, pratique uma gentileza sem que ninguém peça.",
"Que o lar seja escola de amor e oficina de perdão.",
"A vida espiritual se revela no trato diário com o próximo.",
"Que Deus abençoe o trabalho, o descanso e a mesa de vocês.",
"Em toda estação da vida, há motivo para agradecer.",
"Que a luz do Evangelho inspire atitudes concretas de bem.",
"Cuidar da alimentação e da água também é espiritualidade prática.",
"Que a união familiar seja o maior tesouro desta casa.",
"A esperança renasce cada vez que escolhemos o amor.",
"Que o dia de hoje deixe um rastro de paz em quem cruzar o caminho de vocês.",
"Respeitar o próprio ritmo é um ato de sabedoria e carinho.",
"Que a mesa de vocês tenha pão, paz e conversa boa.",
"Um coração grato enxerga bênçãos onde outros veem rotina.",
"Que a honestidade e a humildade adornem o caráter de cada dia.",
"O Evangelho se pratica no modo como tratamos quem mora conosco.",
"Que a chuva lave preocupações e o sol aqueça a esperança.",
"Hoje, escolha ser instrumento de consolação.",
"Que a oração fortaleça a saúde emocional de toda a família.",
"A paciência com os pais e com os filhos é semente de harmonia.",
"Que o Senhor multiplique dias de bem-estar em Venâncio Aires.",
"Caminhar devagar também é chegar, quando se caminha com fé.",
"Que o silêncio orante cure o que as palavras não alcançam.",
"A caridade começa ao não ferir com a língua.",
"Que a alegria do dever cumprido traga paz à noite.",
"Beber água ao longo do dia é cuidar do templo que Deus confiou a você.",
"Que a esperança seja mais forte do que o cansaço.",
"Um lar abençoado se reconhece pela delicadeza entre as pessoas.",
"Que o bem feito hoje abra portas amanhã.",
"A fé amadurece quando enfrentamos o dia sem perder a doçura.",
"Que Ivone e Osvaldo se sintam rodeados de proteção e carinho.",
"Hoje é dia de cultivar saúde, fé e afeto — os três juntos.",
])

affirmations = [
"Eu acolho este dia com serenidade e confiança.",
"Sou amado(a), protegido(a) e capaz de recomeçar.",
"Escolho alimentar pensamentos de paz.",
"Minha fé é maior do que as inquietações deste momento.",
"Posso caminhar devagar, sem deixar de seguir em frente.",
"O bem que faço também floresce dentro de mim.",
"Eu mereço descansar e receber carinho.",
"Confio que cada dia traz uma nova possibilidade.",
"Minha presença é importante para as pessoas que me amam.",
"Hoje escolho tratar a mim mesmo(a) com gentileza.",
"Cuido do meu corpo com gratidão e responsabilidade.",
"Bebo água e respeito os sinais da minha saúde.",
"A paz mora na minha casa e no meu coração.",
"Sou instrumento de bem na minha família.",
"Deus caminha comigo em cada hora deste dia.",
"Escolho alimentos que nutrem corpo e espírito.",
"Minha saúde importa e merece atenção diária.",
"Sou capaz de hábitos simples e constantes.",
"Agradeço pela vida e cuido dela com zelo.",
"Hoje caminho com fé, paciência e esperança.",
]

bible_stories = [
{"title":"O Bom Samaritano","ref":"Lucas 10:25-37","story":"Um homem ferido à beira do caminho foi ignorado por alguns, mas um samaritano parou, cuidou das feridas e pagou a hospedagem.","lesson":"Ser boa pessoa é ajudar quem precisa, mesmo quando ninguém está olhando e mesmo quando a pessoa é diferente de nós."},
{"title":"A ovelha perdida","ref":"Lucas 15:1-7","story":"O pastor deixa as noventa e nove ovelhas para buscar a que se perdeu, e se alegra ao encontrá-la.","lesson":"Ninguém é descartável. Cuidar de quem está frágil ou distante é um ato de amor verdadeiro."},
{"title":"O filho pródigo","ref":"Lucas 15:11-32","story":"Um filho desperdiça a herança, sofre e volta para casa. O pai corre ao encontro dele e o recebe com festa.","lesson":"Perdoar e acolher quem se arrepende reconstrói famílias e cura corações."},
{"title":"Jesus lava os pés dos discípulos","ref":"João 13:1-17","story":"Antes da ceia, Jesus lava os pés dos discípulos, ensinando pelo exemplo.","lesson":"A grandeza está em servir com humildade, não em mandar com orgulho."},
{"title":"A viúva pobre","ref":"Marcos 12:41-44","story":"Enquanto muitos davam muito do que lhes sobrava, uma viúva deu duas pequenas moedas — tudo o que tinha.","lesson":"O valor de um gesto está no coração, não no tamanho aparente da oferta."},
{"title":"Daniel na cova dos leões","ref":"Daniel 6","story":"Daniel continua orando a Deus mesmo sob ameaça e é protegido na cova dos leões.","lesson":"A fidelidade a Deus e à consciência reta traz coragem nos momentos difíceis."},
{"title":"José no Egito","ref":"Gênesis 37–50","story":"José é vendido pelos irmãos, sofre injustiças, mas depois perdoa e salva a família da fome.","lesson":"O perdão e a integridade podem transformar dor em bênção para muita gente."},
{"title":"Rute e Noemi","ref":"Rute 1–4","story":"Rute permanece ao lado da sogra Noemi na viuvez e na pobreza, com lealdade e cuidado.","lesson":"Fidelidade e cuidado com a família são caminhos de amor e de providência."},
{"title":"Davi e Golias","ref":"1 Samuel 17","story":"O jovem Davi enfrenta o gigante Golias com fé, coragem e uma funda simples.","lesson":"Com fé e propósito, desafios grandes podem ser enfrentados sem arrogância."},
{"title":"A mulher samaritana","ref":"João 4:1-42","story":"Jesus conversa com uma mulher rejeitada socialmente e oferece água viva — dignidade e esperança.","lesson":"Tratar cada pessoa com dignidade revela o caráter de quem segue o bem."},
{"title":"Pedro anda sobre as águas","ref":"Mateus 14:22-33","story":"Pedro caminha sobre a água ao olhar para Jesus; quando teme, começa a afundar e é amparado.","lesson":"A fé nos sustenta; quando o medo vem, podemos pedir ajuda e ser erguidos."},
{"title":"A multiplicação dos pães","ref":"João 6:1-14","story":"Com cinco pães e dois peixes, Jesus alimenta uma multidão.","lesson":"Quando oferecemos o pouco que temos com generosidade, o bem se multiplica."},
{"title":"Zaqueu","ref":"Lucas 19:1-10","story":"Zaqueu, cobrador de impostos, sobe numa árvore para ver Jesus e muda de vida ao ser acolhido.","lesson":"O encontro com o bem pode transformar hábitos injustos em restituição e honestidade."},
{"title":"A tempestade acalmada","ref":"Marcos 4:35-41","story":"Os discípulos temem o naufrágio; Jesus acalma o vento e o mar.","lesson":"Em meio a tempestades da vida, a fé traz paz mesmo antes da situação mudar."},
{"title":"O amigo à meia-noite","ref":"Lucas 11:5-8","story":"Um homem insiste em pedir pão ao amigo durante a noite para atender um visitante.","lesson":"Persistir no bem e na oração, com humildade, é virtude."},
{"title":"A cura do cego Bartimeu","ref":"Marcos 10:46-52","story":"Bartimeu grita por misericórdia; mesmo repreendido, insiste e Jesus restaura sua vista.","lesson":"Não desista de buscar luz, cura e dignidade — a fé perseverante abre caminhos."},
{"title":"Marta e Maria","ref":"Lucas 10:38-42","story":"Marta se afoba com tarefas; Maria escolhe ouvir. Jesus valoriza o essencial.","lesson":"Servir é bom, mas não devemos esquecer de escutar, orar e estar presentes."},
{"title":"O grão de mostarda","ref":"Mateus 13:31-32","story":"Jesus compara o Reino a um grão pequenino que se torna árvore grande.","lesson":"Pequenos atos de fé e bondade crescem e abrigam muita vida."},
{"title":"A parábola dos talentos","ref":"Mateus 25:14-30","story":"Servos recebem talentos; os que os fazem frutificar são elogiados.","lesson":"Usar bem os dons que temos — saúde, tempo, carinho — é responsabilidade amorosa."},
{"title":"As bem-aventuranças","ref":"Mateus 5:1-12","story":"Jesus ensina que os mansos, misericordiosos e pacificadores são bem-aventurados.","lesson":"A verdadeira felicidade nasce do caráter bondoso, não da vaidade."},
{"title":"O fariseu e o publicano","ref":"Lucas 18:9-14","story":"Um se orgulha na oração; o outro pede misericórdia com humildade.","lesson":"A humildade aproxima de Deus; o orgulho afasta do amor verdadeiro."},
{"title":"A mulher adúltera","ref":"João 8:1-11","story":"A multidão quer condenar; Jesus convida quem não tem pecado a atirar a primeira pedra e oferece recomeço.","lesson":"Não julgue com dureza. Ofereça caminho de recomeço com verdade e misericórdia."},
{"title":"Elias e a viúva de Sarepta","ref":"1 Reis 17:8-16","story":"Em tempo de fome, uma viúva divide o pouco que tem e a provisão não falta.","lesson":"A generosidade, mesmo no aperto, abre espaço para a providência."},
{"title":"Noé e a arca","ref":"Gênesis 6–9","story":"Noé obedece a Deus, constrói a arca e preserva a vida através da tempestade.","lesson":"Obediência paciente e cuidado com a vida protegem o futuro."},
{"title":"Abraão e a hospitalidade","ref":"Gênesis 18:1-8","story":"Abraão recebe estrangeiros com pressa generosa, oferecendo sombra, água e refeição.","lesson":"Acolher o outro com prontidão é uma forma concreta de fé."},
{"title":"Moisés e a sarça ardente","ref":"Êxodo 3","story":"Deus chama Moisés de uma sarça que arde sem se consumir e o envia para libertar o povo.","lesson":"Mesmo inseguros, podemos responder ao chamado do bem com coragem."},
{"title":"A cura do servo do centurião","ref":"Mateus 8:5-13","story":"Um centurião pede a cura do servo com fé humilde, reconhecendo a autoridade de Jesus.","lesson":"Cuidar de quem trabalha conosco e confiar com humildade são atitudes nobres."},
{"title":"Paulo e Silas na prisão","ref":"Atos 16:16-34","story":"Presos injustamente, oram e cantam; um carcereiro é tocado e toda a casa encontra esperança.","lesson":"Mesmo na prova, a fé e a bondade podem iluminar outras pessoas."},
{"title":"A criação e o cuidado","ref":"Gênesis 1–2","story":"Deus cria o mundo com ordem e bondade e confia ao ser humano o cuidado da criação.","lesson":"Cuidar da saúde, da casa, da natureza e do próximo é participar do cuidado divino."},
{"title":"O jovem rico","ref":"Marcos 10:17-22","story":"Um jovem cumpre regras, mas não consegue soltar o apego às riquezas para seguir plenamente.","lesson":"Ser boa pessoa envolve desapego e generosidade, não só aparência de virtude."},
{"title":"A parábola do semeador","ref":"Mateus 13:1-23","story":"A semente cai em terrenos diferentes; só a terra boa produz fruto duradouro.","lesson":"Prepare o coração com atenção, humildade e constância para o bem crescer."},
{"title":"Jesus e as crianças","ref":"Marcos 10:13-16","story":"Os discípulos afastam as crianças; Jesus as acolhe e as abençoa.","lesson":"Trate os mais frágeis com respeito, tempo e carinho — o Reino pertence aos de coração simples."},
{"title":"A cura do paralítico","ref":"Marcos 2:1-12","story":"Amigos abrem o teto para levar o paralítico até Jesus.","lesson":"Amizade verdadeira carrega o outro quando ele não consegue andar sozinho."},
{"title":"Ester e a coragem","ref":"Ester 4–7","story":"Ester arrisca a própria segurança para interceder pelo seu povo.","lesson":"A coragem a serviço do bem coletivo é uma forma elevada de amor."},
{"title":"A paz que o mundo não dá","ref":"João 14:27","story":"Jesus oferece uma paz diferente da paz superficial do mundo.","lesson":"Cultive a paz interior pela fé, para então espalhá-la em casa e na comunidade."},
{"title":"O fruto do Espírito","ref":"Gálatas 5:22-23","story":"Paulo descreve o fruto do Espírito: amor, alegria, paz, paciência, amabilidade, bondade, fidelidade, mansidão e domínio próprio.","lesson":"Ser boa pessoa é deixar esses frutos aparecerem nas atitudes diárias."},
{"title":"A casa sobre a rocha","ref":"Mateus 7:24-27","story":"Quem ouve e pratica as palavras de Jesus constrói sobre a rocha; quem só ouve, sobre a areia.","lesson":"Ouvir o bem não basta: é preciso praticá-lo para a vida resistir às tempestades."},
{"title":"O perdão de setenta vezes sete","ref":"Mateus 18:21-22","story":"Pedro pergunta quantas vezes perdoar; Jesus amplia o horizonte do perdão.","lesson":"O perdão perseverante libera a alma e restaura relações."},
{"title":"A luz do mundo","ref":"Mateus 5:14-16","story":"Jesus chama seus seguidores a serem luz, para que vejam suas boas obras e glorifiquem a Deus.","lesson":"Suas atitudes boas podem iluminar a casa e inspirar outras pessoas."},
{"title":"O novo mandamento","ref":"João 13:34-35","story":"Jesus manda amar uns aos outros como Ele amou.","lesson":"O sinal mais claro de uma vida boa é o amor prático no dia a dia."},
]

days_pt = ["Segunda","Terça","Quarta","Quinta","Sexta","Sábado","Domingo"]

def week_menu(prefix_meals):
    return [{"day": days_pt[i], **prefix_meals[i % len(prefix_meals)]} for i in range(7)]

diets = {
    "underweight": {
        "label": "Abaixo do peso",
        "goal": "Ganhar peso com saúde, priorizando nutrientes e refeições regulares.",
        "prep": [
            "Faça 5–6 refeições menores ao dia, sem pular café da manhã.",
            "Acrescente azeite, pasta de amendoim, ovos, queijo branco e vitamina com leite/aveia.",
            "Cozinhe sopas cremosas e mingaus; facilite a mastigação se necessário.",
            "Beba água entre as refeições, não em excesso durante a refeição.",
        ],
        "week": week_menu([
            {"breakfast":"Vitamina de banana com aveia e leite","lunch":"Arroz, feijão, frango desfiado e legumes refogados","snack":"Iogurte natural com mel e castanhas","dinner":"Sopa de legumes com carne e torrada"},
            {"breakfast":"Pão integral com ovo mexido e suco natural","lunch":"Purê de batata, peixe assado e salada","snack":"Vitamina de abacate","dinner":"Macarrão com molho de carne moída e queijo"},
            {"breakfast":"Mingau de aveia com banana","lunch":"Arroz, lentilha, omelete e cenoura","snack":"Pão com pasta de amendoim","dinner":"Canja de galinha com legumes"},
            {"breakfast":"Tapioca com queijo e mamão","lunch":"Arroz, feijão, carne magra e abobrinha","snack":"Mix de frutas com iogurte","dinner":"Risoto simples de frango"},
            {"breakfast":"Cuscuz com ovo e café com leite","lunch":"Batata-doce, peito de frango e salada","snack":"Vitamina de morango/leite","dinner":"Sopa de feijão com legumes"},
            {"breakfast":"Panqueca de aveia com banana","lunch":"Arroz, grão-de-bico, peixe e salada","snack":"Queijo branco com goiabada light","dinner":"Omelete recheada com legumes"},
            {"breakfast":"Vitamina completa (leite, aveia, fruta, pasta de amendoim)","lunch":"Arroz, feijão, assado e salada colorida","snack":"Castanhas e fruta","dinner":"Creme de milho com frango desfiado"},
        ]),
    },
    "normal": {
        "label": "Peso adequado",
        "goal": "Manter o equilíbrio com variedade, fibras e hidratação.",
        "prep": [
            "Monte o prato: 1/2 legumes, 1/4 proteína, 1/4 carboidrato.",
            "Tempere com ervas, alho, cebola e azeite; evite fritura frequente.",
            "Prefira grelhados, assados, cozidos e refogados leves.",
            "Mantenha horários regulares e mastigue devagar.",
        ],
        "week": week_menu([
            {"breakfast":"Fruta + aveia + iogurte","lunch":"Arroz integral, feijão, frango grelhado e salada","snack":"Castanhas ou fruta","dinner":"Sopa de legumes com ovo"},
            {"breakfast":"Pão integral com ovo e café","lunch":"Purê, peixe e legumes no vapor","snack":"Vitamina leve","dinner":"Salada completa com grãos e frango"},
            {"breakfast":"Tapioca com queijo branco","lunch":"Arroz, lentilha, carne magra e salada","snack":"Iogurte","dinner":"Omelete com salada"},
            {"breakfast":"Mingau de aveia","lunch":"Quinoa/arroz, grão-de-bico e legumes","snack":"Fruta","dinner":"Sopa cremosa de abóbora"},
            {"breakfast":"Cuscuz com ovo","lunch":"Arroz, feijão, peixe e salada","snack":"Chá e biscoito integral","dinner":"Wrap de frango com salada"},
            {"breakfast":"Vitamina de banana","lunch":"Batata-doce, frango e brócolis","snack":"Mix de frutas","dinner":"Risoto de legumes"},
            {"breakfast":"Pão, queijo branco e fruta","lunch":"Arroz, feijão, assado e salada","snack":"Iogurte natural","dinner":"Caldo verde leve"},
        ]),
    },
    "overweight": {
        "label": "Sobrepeso",
        "goal": "Reduzir peso com calma, priorizando saciedade e consistência.",
        "prep": [
            "Troque frituras por grelhados/assados e use airfryer/forno se possível.",
            "Aumente legumes e saladas no início da refeição.",
            "Reduza refrigerante, sucos doces e excesso de pão branco.",
            "Cozinhe em quantidade e porcione; evite comer direto da panela.",
        ],
        "week": week_menu([
            {"breakfast":"Ovo + fruta + chá","lunch":"Salada grande, frango grelhado e pouco arroz","snack":"Iogurte natural","dinner":"Sopa de legumes sem batata em excesso"},
            {"breakfast":"Aveia com morango","lunch":"Peixe, legumes e quinoa","snack":"Castanhas (pequena porção)","dinner":"Omelete de claras/ovos com salada"},
            {"breakfast":"Tapioca fina com queijo branco","lunch":"Carne magra, legumes e salada","snack":"Fruta","dinner":"Caldo de legumes com frango"},
            {"breakfast":"Iogurte com chia","lunch":"Frango, brócolis e batata-doce pequena","snack":"Chá e fruta","dinner":"Salada completa com grão-de-bico"},
            {"breakfast":"Vitamina sem açúcar","lunch":"Peixe, salada e legumes","snack":"Iogurte","dinner":"Sopa leve + ovo"},
            {"breakfast":"Ovo mexido e tomate","lunch":"Lentilha, salada e frango","snack":"Fruta","dinner":"Abobrinha recheada com carne magra"},
            {"breakfast":"Aveia + banana pequena","lunch":"Salada, grãos e proteína magra","snack":"Castanhas","dinner":"Sopa ou omelete + salada"},
        ]),
    },
    "obesity": {
        "label": "Obesidade",
        "goal": "Cuidado gradual, com acompanhamento médico quando possível, e hábitos sustentáveis.",
        "prep": [
            "Foque em refeições caseiras simples: proteína magra + muita salada/legumes.",
            "Evite ultraprocessados; beba água antes das refeições.",
            "Cozinhe no vapor, assado ou refogado com pouco óleo.",
            "Caminhe leve após as refeições, se houver orientação de saúde.",
        ],
        "week": week_menu([
            {"breakfast":"Ovo + fruta + água","lunch":"Salada abundante + frango grelhado","snack":"Iogurte natural","dinner":"Sopa de legumes"},
            {"breakfast":"Chá + 1 fruta + aveia pequena","lunch":"Peixe + legumes","snack":"Gelatina light ou fruta","dinner":"Omelete + salada"},
            {"breakfast":"Iogurte natural","lunch":"Carne magra + salada colorida","snack":"Fruta","dinner":"Caldo de legumes"},
            {"breakfast":"Vitamina sem açúcar","lunch":"Frango + brócolis + pouca batata-doce","snack":"Chá","dinner":"Sopa + ovo"},
            {"breakfast":"Ovo e tomate","lunch":"Peixe + salada","snack":"Iogurte","dinner":"Legumes assados + proteína"},
            {"breakfast":"Aveia com canela","lunch":"Lentilha + salada + frango","snack":"Fruta","dinner":"Sopa cremosa de abóbora (leve)"},
            {"breakfast":"Chá e fruta","lunch":"Salada completa + proteína magra","snack":"Água de coco / água","dinner":"Omelete de legumes"},
        ]),
    },
}

weather_tips = {
    "clear": {
        "title": "Dia de sol",
        "tips": ["Use chapéu ou protetor solar se sair","Beba água com mais frequência","Prefira sombra nos horários mais quentes","Ventile a casa pela manhã"],
    },
    "cloudy": {
        "title": "Tempo nublado",
        "tips": ["Mantenha a rotina de hidratação mesmo sem calor aparente","Aproveite para caminhar leve se não chover","Cuide da iluminação interna para o ânimo","Vista camadas leves"],
    },
    "rain": {
        "title": "Chuva",
        "tips": ["Evite molhar os pés e seque bem a roupa","Beba água em temperatura ambiente","Cuidado com piso escorregadio","Use o dia para oração, leitura e descanso"],
    },
    "storm": {
        "title": "Temporal",
        "tips": ["Fique em local seguro e evite áreas abertas","Desligue aparelhos da tomada se houver raios","Tenha lanterna e água por perto","Mantenha a calma com respiração e prece"],
    },
    "wind": {
        "title": "Vento forte",
        "tips": ["Segure bem portas e janelas","Cuidado com poeira nos olhos","Hidrate a pele e a garganta","Evite caminhar perto de árvores instáveis"],
    },
    "dry": {
        "title": "Tempo seco",
        "tips": ["Beba água mesmo sem sede","Use umedecedor ou toalha úmida no ambiente","Evite exposição prolongada ao sol e poeira","Prefira alimentos suculentos (frutas, sopas)"],
    },
    "cold": {
        "title": "Tempo frio",
        "tips": ["Vista camadas e proteja pescoço e pés","Tome líquidos morno (chá, sopa)","Mantenha a casa ventilada sem correntes fortes","Não pule refeições; o corpo gasta energia para se aquecer"],
    },
    "hot": {
        "title": "Calor intenso",
        "tips": ["Beba água a cada hora","Evite esforço pesado no pico do calor","Use roupas leves e claras","Faça refeições mais leves e frescas"],
    },
}

payload = {
    "greetings": greetings,
    "dailyMessages": daily_messages,
    "affirmations": affirmations,
    "bibleStories": bible_stories,
    "diets": diets,
    "weatherTips": weather_tips,
}

counts = {p: {k: len(v) for k, v in d.items()} for p, d in greetings.items()}
js = "window.CANTINHO_CONTENT = " + json.dumps(payload, ensure_ascii=False) + ";\n"
(ROOT / "content.js").write_text(js, encoding="utf-8")
print("OK", counts, "daily", len(daily_messages), "stories", len(bible_stories))
